// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cburpyzmvdgypjjdpoup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidXJweXptdmRneXBqamRwb3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNzgyMDQsImV4cCI6MjA1MjY1NDIwNH0.9KSygyVYef8IuEXgI71-78rR4ttkwNq4tb6clr4vVyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);